language: node_js
node_js: 
  - "11.9.0"

before_script:
  - cd ./backend && npm run bootstrap

script:
  - npm run test

after_success:
  - npm run docs

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: backend/docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true